version: "3"
services:
  db:
    container_name: ${APP_NAME}_mysql
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - "${MYSQL_PORTS}:3306"
    volumes:
      - /${APP_PATH}/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db:/var/lib/mysql
    networks:
      - app-network
  redis:
    container_name: ${APP_NAME}_redis
    image: redis:5.0.3
    ports:
      - "${REDIS_PORTS}:6379"
    volumes:
      - redis:/data
    networks:
      - app-network
    environment:
      - TZ=${TIMEZONE}
    command: redis-server --requirepass ${REDIS_PASSWORD}
  php:
    container_name: ${APP_NAME}_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - /${APP_PATH}/www/${APP_CODE_PATH}:/www
      - /${APP_PATH}/php/supervisor/conf.d:/etc/supervisor/conf.d
      - /${APP_PATH}/php/supervisor/log:/var/log/supervisor
    networks:
      - app-network
    environment:
      - TZ=${TIMEZONE}
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:1.15.7
    ports:
      - "${NGINX_PORTS}:80"
    depends_on:
      - php
    volumes:
      - /${APP_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - /${APP_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /${APP_PATH}/nginx/log:/var/log/nginx
      - /${APP_PATH}/www/${APP_CODE_PATH}:/www
    environment:
      - TZ=${TIMEZONE}
    networks:
      - app-network
volumes:
  db:
    driver: local
  redis:
    driver: local
networks:
  app-network:
    driver: bridge